services:
  volume-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: standalone-volume-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Override any environment variables here if needed
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount logs directory for persistence (optional)
      - ./logs:/app/logs:rw
    networks:
      - volume-bot-network
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a monitoring service
  # monitoring:
  #   image: prom/prometheus:latest
  #   container_name: volume-bot-monitoring
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - volume-bot-network

networks:
  volume-bot-network:
    driver: bridge

volumes:
  logs:
    driver: local